# Generated by Django 5.1.4 on 2025-01-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connection', '0002_contentconnection_answer_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentconnection',
            name='answer_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
