# Generated by Django 5.1 on 2025-01-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Connection', '0003_alter_contentconnection_answer_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentconnection',
            name='status',
        ),
    ]
