# Generated by Django 5.1.4 on 2025-02-01 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connection', '0004_remove_contentconnection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentconnection',
            name='link',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=122)),
                ('post_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='POST_CON', to='Connection.contentconnection')),
            ],
        ),
    ]
