# Generated by Django 5.1.4 on 2025-02-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connection', '0005_contentconnection_link_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentconnection',
            name='link',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
    ]
