# Generated by Django 5.1.4 on 2025-02-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connection', '0007_rename_appendix_contentconnection_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentconnection',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
